### ISSUE TITLE
Error constructing GoogleGroupToDiscourse

### ISSUE THREAD

**Issue by malmaud** [pacharanero/google-groups-scraper#2]
I'm getting

```
Selenium::WebDriver::Error::NoSuchElementError: Unable to locate element: {"method":"id","selector":"Email"}
```

**Comment by malmaud** [comment]
NM, i just made the necessary edits to deal with the changes in element names.

**Comment by pacharanero** [comment]
​Great. Let me know how useful you find the scraper.
​If you make any amendments then I'm happy to take pull requests
M
